### ISSUE TITLE
Datapack issues

### ISSUE THREAD

**Issue by Fourmisain** [FettLol/fettlol-modpack#1]
Loading [More Villages](https://www.planetminecraft.com/data-pack/more-villages-4819384/) prints

> [main/ERROR] [class_5485]: Structure start: Not a JSON object: "minecraft:ruined_portal_desert"; Not a JSON object: "minecraft:stronghold"; Not a JSON object: "minecraft:mineshaft"; Not a JSON object: "minecraft:desert_pyramid"; Not a JSON object: "minecraft:pillager_outpost"; Not a JSON object: "minecraft:village_desert"; Not a JSON object: "gatkong:desert_maze"

May be related to [MC-196068](https://bugs.mojang.com/browse/MC-196068).
I've reported this to the author.

---

It seems [The Forbidden Castle](https://www.planetminecraft.com/data-pack/nether-castles-standalone/) is causing some errors too, but I couldn't reproduce it by itself, only on fettlol 1.12 so far:
https://0bin.net/paste/Q4trftZ3#ZYUH6oipn-lF1DqBmVYcV0pe4gn5c4TxN+PUkgo2knr
(Totally legit paste service, buy your Bitcoins today and don't forget to tip! \</s>)

**Comment by BrekiTomasson** [comment]
For info: The Forbidden Castle will be removed in modpack v1.12, so we can ignore it in the troubleshooting for now. While I definitely enjoyed the structure it adds, I found that it also added so many new things, such as spells (via function calls), custom items and so on. Also, due to the rarity of the structure, I felt that the benefits of keeping it was just not enough to keep it in.

As for the remaining errors, this is something that I've encountered in a number of datapacks that add structures and so on, and remember seeing various things causing problems during various versions of Minecraft 1.16.x, most likely due to the large amount of changes they've made to the way code that handles custom biomes, structures, etc.

I reported this to the author 4 months ago; here's the conversation we had at the time:

![image](https://user-images.githubusercontent.com/7026735/113196295-9db16b80-9263-11eb-994c-de6eeaa58cc0.png)
